### ISSUE TITLE
Crash report from WebStorm - v0.60.0

### ISSUE THREAD

**Issue by objarni** [intellij-purescript/intellij-purescript#318]
Leaving in case maintainer(s) are into some digging :)

```java.lang.NullPointerException: npmProc.inputStream.bufferedReader().readLine() must not be null
	at org.purescript.ide.purs.Npm$Companion.run(Npm.kt:23)
	at org.purescript.ide.purs.Npm$Companion.access$run(Npm.kt:11)
	at org.purescript.ide.purs.Npm$Companion$localBinPath$2.invoke(Npm.kt:12)
	at org.purescript.ide.purs.Npm$Companion$localBinPath$2.invoke(Npm.kt:12)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.purescript.ide.purs.Npm$Companion.getLocalBinPath(Npm.kt:12)
	at org.purescript.ide.purs.Npm$Companion.pathFor(Npm.kt:33)
	at org.purescript.ide.purs.StartupActivity.runActivity(StartupActivity.kt:22)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.runStartupActivity(StartupManagerImpl.kt:511)
	at com.intellij.ide.startup.impl.StartupManagerImplKt.access$runStartupActivity(StartupManagerImpl.kt:1)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:305)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:296)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$1.run(StartupManagerImpl.kt:247)
	at com.intellij.openapi.project.DumbServiceImpl.runWithWaitForSmartModeDisabled(DumbServiceImpl.java:650)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:246)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1.accept(StartupManagerImpl.kt:70)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.openapi.extensions.ExtensionPointName.processWithPluginDescriptor(ExtensionPointName.java:143)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:241)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:189)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1$lambda$1.invoke(StartupManagerImpl.kt:70)
	at com.intellij.ide.startup.impl.StartupManagerImplKt$sam$java_lang_Runnable$0.run(StartupManagerImpl.kt)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:365)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:343)
	at com.intellij.ide.startup.impl.StartupManagerImpl$projectOpened$$inlined$forkJoinTask$1.run(trace.kt:90)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1375)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Neppord** [comment]
It seams like the top of the stack trace is missing. The original Exception and message is missing for example. Could you reproduce with new version and replace with full stack trace, thanks! :)

What platform was this on, was it Mac?

**Comment by objarni** [comment]
Maybe this is complete?

```java.lang.NullPointerException: npmProc.inputStream.bufferedReader().readLine() must not be null
	at org.purescript.ide.purs.Npm.run(Npm.kt:36)
	at org.purescript.ide.purs.Npm.access$run(Npm.kt:12)
	at org.purescript.ide.purs.Npm$localBinPath$2.invoke(Npm.kt:15)
	at org.purescript.ide.purs.Npm$localBinPath$2.invoke(Npm.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.purescript.ide.purs.Npm.getLocalBinPath(Npm.kt:15)
	at org.purescript.ide.purs.Npm.pathFor(Npm.kt:46)
	at org.purescript.ide.purs.StartupActivity.runActivity(StartupActivity.kt:23)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:279)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:278)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:278)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by objarni** [comment]
Weird, Ctrl+A, Ctrl+C does not copy the whole text area in plugin crash report window, WebStorm latest. Trying once more, this time with mouse drag from top to bottom:

```java.lang.NullPointerException: npmProc.inputStream.bufferedReader().readLine() must not be null
	at org.purescript.ide.purs.Npm.run(Npm.kt:36)
	at org.purescript.ide.purs.Npm.access$run(Npm.kt:12)
	at org.purescript.ide.purs.Npm$localBinPath$2.invoke(Npm.kt:15)
	at org.purescript.ide.purs.Npm$localBinPath$2.invoke(Npm.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.purescript.ide.purs.Npm.getLocalBinPath(Npm.kt:15)
	at org.purescript.ide.purs.Npm.pathFor(Npm.kt:46)
	at org.purescript.ide.purs.StartupActivity.runActivity(StartupActivity.kt:23)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:279)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:278)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:278)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runPostStartupActivities(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runStartupActivities$2.invokeSuspend(StartupManagerImpl.kt:184)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

**Comment by objarni** [comment]
No that's not it. I verified the whole text was with triple back ticks before commenting. Something in the stack trace is breaking of the markup.

This is the top half of the stack trace:

```java.lang.NullPointerException: npmProc.inputStream.bufferedReader().readLine() must not be null
	at org.purescript.ide.purs.Npm.run(Npm.kt:36)
	at org.purescript.ide.purs.Npm.access$run(Npm.kt:12)
	at org.purescript.ide.purs.Npm$localBinPath$2.invoke(Npm.kt:15)
	at org.purescript.ide.purs.Npm$localBinPath$2.invoke(Npm.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.purescript.ide.purs.Npm.getLocalBinPath(Npm.kt:15)
	at org.purescript.ide.purs.Npm.pathFor(Npm.kt:46)
	at org.purescript.ide.purs.StartupActivity.runActivity(StartupActivity.kt:23)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:340)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$runActivityAndMeasureDuration(StartupManagerImpl.kt:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:279)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$2$2$1.invoke(StartupManagerImpl.kt:278)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob$lambda-0(cancellation.kt:17)
	at com.intellij.openapi.progress.Cancellation.withCurrentJob(Cancellation.java:60)
	at com.intellij.openapi.progress.CancellationKt.withCurrentJob(cancellation.kt:17)
	at com.intellij.openapi.progress.CoroutinesKt.blockingContext(coroutines.kt:142)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runPostStartupActivities(StartupManagerImpl.kt:278)
	at 
```

**Comment by objarni** [comment]
Giving up on GH md. Mailing to you instead, as attached file!

**Comment by Neppord** [comment]
For traceability
```
java.lang.NullPointerException: npmProc.inputStream.bufferedReader().readLine() must not be null
at org.purescript.ide.purs.Npm.run(Npm.kt:36)
```

the `ProcessBuilder` API is lying, and things can be null even though the types says otherwise. It seams like if nothing is written to the `InputStream` that is the output of the program (yes i know, super confusing) then its never set but instead is `null`.
