### ISSUE TITLE
could not parse value of case alternative 

### ISSUE THREAD

**Issue by drathier** [intellij-purescript/intellij-purescript#374]
```
java.lang.IllegalStateException: could not parse value of case alternative 
	at org.purescript.module.declaration.value.expression.controll.caseof.CaseAlternative.getValue(CaseAlternative.kt:16)
	at org.purescript.module.declaration.value.expression.controll.caseof.CaseAlternative.unify(CaseAlternative.kt:25)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.controll.caseof.CaseAlternative.inferType(CaseAlternative.kt:14)
	at org.purescript.module.declaration.value.expression.controll.caseof.PSCase.unify(PSCase.kt:14)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.controll.caseof.PSCase.inferType(PSCase.kt:9)
	at org.purescript.module.declaration.value.expression.PSParens.unify(PSParens.kt:10)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.ExpressionAtom$DefaultImpls.inferType(ExpressionAtom.kt:5)
	at org.purescript.module.declaration.value.expression.PSParens.inferType(PSParens.kt:7)
	at org.purescript.module.declaration.value.ValueDecl.unify(ValueDecl.kt:156)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDecl.inferType(ValueDecl.kt:34)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.unify(ValueDeclarationGroup.kt:157)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.inferType(ValueDeclarationGroup.kt:32)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.unify(PSExpressionIdentifier.kt:94)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.ExpressionAtom$DefaultImpls.inferType(ExpressionAtom.kt:5)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.inferType(PSExpressionIdentifier.kt:31)
	at org.purescript.module.declaration.value.expression.literals.PSArrayLiteral.unify(PSArrayLiteral.kt:14)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Atom.unify(OperatorExpression.kt:42)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$DefaultImpls.inferType(OperatorExpression.kt:22)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Atom.inferType(OperatorExpression.kt:38)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Operator.unify(OperatorExpression.kt:79)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$DefaultImpls.inferType(OperatorExpression.kt:22)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Operator.inferType(OperatorExpression.kt:72)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Operator.unify(OperatorExpression.kt:79)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$DefaultImpls.inferType(OperatorExpression.kt:22)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Operator.inferType(OperatorExpression.kt:72)
	at org.purescript.module.declaration.value.expression.OperatorExpression.unify(OperatorExpression.kt:21)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.OperatorExpression.inferType(OperatorExpression.kt:17)
	at org.purescript.module.declaration.value.ValueDecl.unify(ValueDecl.kt:156)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDecl.inferType(ValueDecl.kt:34)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.unify(ValueDeclarationGroup.kt:157)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.inferType(ValueDeclarationGroup.kt:32)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.unify(PSExpressionIdentifier.kt:94)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.ExpressionAtom$DefaultImpls.inferType(ExpressionAtom.kt:5)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.inferType(PSExpressionIdentifier.kt:31)
	at org.purescript.module.declaration.value.expression.identifier.Argument.unify(Argument.kt:13)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Argument.inferType(Argument.kt:9)
	at org.purescript.module.declaration.value.expression.identifier.Call.unify(Call.kt:19)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Call.inferType(Call.kt:10)
	at org.purescript.module.declaration.value.ValueDecl.unify(ValueDecl.kt:156)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDecl.inferType(ValueDecl.kt:34)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.unify(ValueDeclarationGroup.kt:157)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.inferType(ValueDeclarationGroup.kt:32)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.unify(PSExpressionIdentifier.kt:94)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.ExpressionAtom$DefaultImpls.inferType(ExpressionAtom.kt:5)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.inferType(PSExpressionIdentifier.kt:31)
	at org.purescript.module.declaration.value.expression.identifier.Call.unify(Call.kt:18)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Call.inferType(Call.kt:10)
	at org.purescript.module.declaration.value.expression.literals.RecordLiteral.unify(RecordLiteral.kt:18)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.ExpressionAtom$DefaultImpls.inferType(ExpressionAtom.kt:5)
	at org.purescript.module.declaration.value.expression.literals.RecordLiteral.inferType(RecordLiteral.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Argument.unify(Argument.kt:13)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Argument.inferType(Argument.kt:9)
	at org.purescript.module.declaration.value.expression.identifier.Call.unify(Call.kt:19)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Call.inferType(Call.kt:10)
	at org.purescript.module.declaration.value.expression.literals.RecordLiteral.unify(RecordLiteral.kt:18)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.ExpressionAtom$DefaultImpls.inferType(ExpressionAtom.kt:5)
	at org.purescript.module.declaration.value.expression.literals.RecordLiteral.inferType(RecordLiteral.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Argument.unify(Argument.kt:13)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Argument.inferType(Argument.kt:9)
	at org.purescript.module.declaration.value.expression.identifier.Call.unify(Call.kt:19)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Call.inferType(Call.kt:10)
	at org.purescript.module.declaration.value.ValueDecl.unify(ValueDecl.kt:156)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDecl.inferType(ValueDecl.kt:34)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.unify(ValueDeclarationGroup.kt:157)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.inferType(ValueDeclarationGroup.kt:32)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.unify(PSExpressionIdentifier.kt:94)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.ExpressionAtom$DefaultImpls.inferType(ExpressionAtom.kt:5)
	at org.purescript.module.declaration.value.expression.identifier.PSExpressionIdentifier.inferType(PSExpressionIdentifier.kt:31)
	at org.purescript.module.declaration.value.expression.identifier.Call.unify(Call.kt:18)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.identifier.Call.inferType(Call.kt:10)
	at org.purescript.module.declaration.value.ValueDecl.unify(ValueDecl.kt:156)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDecl.inferType(ValueDecl.kt:34)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.unify(ValueDeclarationGroup.kt:157)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.inferType(ValueDeclarationGroup.kt:32)
	at org.purescript.module.declaration.SignatureInlayHintProvider$createCollector$1.collectFromElement(SignatureInlayHintProvider.kt:84)
	at com.intellij.codeInsight.hints.declarative.impl.DeclarativeInlayHintsPass.doCollectInformation(DeclarativeInlayHintsPass.kt:45)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by Neppord** [comment]
Im closing this issue since its almost a year old, and things might have changed.

feel free to reopen it if you see this again.
