### ISSUE TITLE
"Failed to pares module"

### ISSUE THREAD

**Issue by drathier** [intellij-purescript/intellij-purescript#376]
```
java.lang.IllegalStateException: Failed to pares module
	at org.purescript.psi.PSPsiElement.getModule(PSPsiElement.kt:20)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Operator.<init>(OperatorExpression.kt:76)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$TmpLeftHand.insertRight(OperatorExpression.kt:63)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$TmpLeftHand.insertRight(OperatorExpression.kt:62)
	at org.purescript.module.declaration.value.expression.OperatorExpression$Tree$Companion.fromElement(OperatorExpression.kt:27)
	at org.purescript.module.declaration.value.expression.OperatorExpression._get_tree_$lambda$0(OperatorExpression.kt:19)
	at com.intellij.psi.util.CachedValuesManager$1.compute(CachedValuesManager.java:158)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:39)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$3(CachedValueBase.java:244)
	at com.intellij.util.CachedValueBase.computeData(CachedValueBase.java:42)
	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$4(CachedValueBase.java:244)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:112)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:66)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:245)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:28)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:69)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:155)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:121)
	at org.purescript.module.declaration.value.expression.OperatorExpression.getTree(OperatorExpression.kt:18)
	at org.purescript.module.declaration.value.expression.OperatorExpression.unify(OperatorExpression.kt:21)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.expression.Expression$DefaultImpls.inferType(Expression.kt:11)
	at org.purescript.module.declaration.value.expression.OperatorExpression.inferType(OperatorExpression.kt:17)
	at org.purescript.module.declaration.value.ValueDecl.unify(ValueDecl.kt:156)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDecl.inferType(ValueDecl.kt:34)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.unify(ValueDeclarationGroup.kt:157)
	at org.purescript.inference.Inferable$DefaultImpls.inferType(Inference.kt:266)
	at org.purescript.module.declaration.value.ValueDeclarationGroup.inferType(ValueDeclarationGroup.kt:32)
	at org.purescript.module.declaration.SignatureInlayHintProvider$createCollector$1.collectFromElement(SignatureInlayHintProvider.kt:84)
	at com.intellij.codeInsight.hints.declarative.impl.DeclarativeInlayHintsPass.doCollectInformation(DeclarativeInlayHintsPass.kt:45)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:57)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:382)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1102)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:373)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:349)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:187)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:347)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)

```

**Comment by i-am-the-slime** [comment]
I fixed this
